# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{icontrol}
  s.version = "0.0.1.pre2"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jose Fernandez (magec)"]
  s.date = %q{2010-08-03}
  s.description = %q{This gem allows you to Connect to a F5 appliance by means of its web services}
  s.email = %q{jfernandezperez@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "icontrol.gemspec",
     "lib/icontrol.rb",
     "lib/icontrol/attributable.rb",
     "lib/icontrol/base.rb",
     "lib/icontrol/common.rb",
     "lib/icontrol/local_lb/common.rb",
     "lib/icontrol/local_lb/monitor.rb",
     "lib/icontrol/local_lb/monitor_rule.rb",
     "lib/icontrol/local_lb/pool.rb",
     "lib/icontrol/local_lb/pool_member.rb",
     "lib/icontrol/local_lb/profile_http_class.rb",
     "lib/icontrol/local_lb/rule.rb",
     "lib/icontrol/local_lb/virtual_server.rb",
     "lib/icontrol/mappings.rb",
     "lib/icontrol/statistic_type.rb",
     "spec/fixtures/endpoint_helper.rb",
     "spec/fixtures/soap/soap_fixture.rb",
     "spec/fixtures/soap/xml/IControl.LocalLB.Pool.create_2d74d0494c49c6dd3114d028a0f8b428_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Pool.create_2d74d0494c49c6dd3114d028a0f8b428_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Pool.get_lb_method_80a2f7c64dd48b949be4d947db6db616_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Pool.get_lb_method_80a2f7c64dd48b949be4d947db6db616_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Pool.get_list_d76a154358eade107434e3d8ae8dd890_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Pool.get_list_d76a154358eade107434e3d8ae8dd890_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Pool.get_member_f83c2f06e546a4ee2c94771571a34bd2_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Pool.get_member_f83c2f06e546a4ee2c94771571a34bd2_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Pool.get_monitor_association_227acb97f0b4d3b065e0c2143f2c3afa_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Pool.get_monitor_association_227acb97f0b4d3b065e0c2143f2c3afa_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Pool.set_monitor_association_82d03563fe5029c9c2e7efb3a9d5c5ee_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Pool.set_monitor_association_82d03563fe5029c9c2e7efb3a9d5c5ee_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.PoolMember.get_object_status_6624c065324e308879b22da56a8cdc52_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.PoolMember.get_object_status_6624c065324e308879b22da56a8cdc52_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.PoolMember.get_object_status_bb6076f8867064a463988dd6adad337b_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.PoolMember.get_object_status_bb6076f8867064a463988dd6adad337b_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.get_host_match_pattern_7608dcc0d0dc37df9f284d690c79f6ab_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.get_host_match_pattern_7608dcc0d0dc37df9f284d690c79f6ab_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.get_list_8f9dacb4578202ac7ddc8e93df2ce338_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.get_list_8f9dacb4578202ac7ddc8e93df2ce338_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.get_path_match_pattern_692221b953b6035d7c1673585c67fb82_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.get_path_match_pattern_692221b953b6035d7c1673585c67fb82_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.get_pool_name_5018b0d4b0feb7684911f72a7e04d332_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.get_pool_name_5018b0d4b0feb7684911f72a7e04d332_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.set_pool_name_3fc042dae8ba8189307e48133473abbf_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.set_pool_name_3fc042dae8ba8189307e48133473abbf_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.set_pool_name_9efa942c734233b042acc0eb233a6850_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.set_pool_name_9efa942c734233b042acc0eb233a6850_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.set_pool_name_d189de926cd730ab919566bbc7aa88e9_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.ProfileHttpClass.set_pool_name_d189de926cd730ab919566bbc7aa88e9_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Rule.get_list_295624e6ef2a1dc1bcca4e4dc4e8ca46_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.Rule.get_list_295624e6ef2a1dc1bcca4e4dc4e8ca46_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_actual_hardware_acceleration_a7519fd1e7d9755335048d16b4e977ee_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_actual_hardware_acceleration_a7519fd1e7d9755335048d16b4e977ee_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_actual_hardware_acceleration_cc032e11d40980dbc1af9600de978d49_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_actual_hardware_acceleration_cc032e11d40980dbc1af9600de978d49_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_clone_pool_387ac8774a7bd8b52b9d12e1353b2158_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_clone_pool_387ac8774a7bd8b52b9d12e1353b2158_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_clone_pool_92c1bbb3597dd3ac311bd491ed942af2_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_clone_pool_92c1bbb3597dd3ac311bd491ed942af2_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_cmp_enable_mode_b2588a81fd25eea0ba4eaf32207e1a44_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_cmp_enable_mode_b2588a81fd25eea0ba4eaf32207e1a44_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_cmp_enable_mode_f87afa0382650ddf0dba2576280fdfb2_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_cmp_enable_mode_f87afa0382650ddf0dba2576280fdfb2_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_connection_limit_504f6088255182695a02a187e4c18716_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_connection_limit_504f6088255182695a02a187e4c18716_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_connection_limit_80d95654cccd735848d8e2c5670fec84_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_connection_limit_80d95654cccd735848d8e2c5670fec84_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_connection_mirror_state_12cf0f506aaaea585c91ec4effc41746_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_connection_mirror_state_12cf0f506aaaea585c91ec4effc41746_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_connection_mirror_state_fc6c1e5a166ce2e4f0889539e1065dbb_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_connection_mirror_state_fc6c1e5a166ce2e4f0889539e1065dbb_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_default_pool_name_d52cd7f67f28cf129bf0b89db974cf89_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_default_pool_name_d52cd7f67f28cf129bf0b89db974cf89_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_destination_290e7e19eb0a17a51f19c89f54e5250b_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_destination_290e7e19eb0a17a51f19c89f54e5250b_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_destination_93c04140b970083bdc22200a196c055c_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_destination_93c04140b970083bdc22200a196c055c_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_enabled_state_4b1359dbe12127831b20de6fd77e5f8f_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_enabled_state_4b1359dbe12127831b20de6fd77e5f8f_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_enabled_state_68eb4b3070c1ac53dd8885c48691eb88_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_enabled_state_68eb4b3070c1ac53dd8885c48691eb88_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_fallback_persistence_profile_582625dcd77a0cf9a95d1765a9bac17e_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_fallback_persistence_profile_582625dcd77a0cf9a95d1765a9bac17e_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_fallback_persistence_profile_e707a38e7406acc44c6ca306bff30170_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_fallback_persistence_profile_e707a38e7406acc44c6ca306bff30170_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_gtm_score_6efd3e48abdd25e650012002742cfacc_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_gtm_score_6efd3e48abdd25e650012002742cfacc_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_httpclass_profile_54e76e4b800313354ac5e0acea7ebec3_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_httpclass_profile_54e76e4b800313354ac5e0acea7ebec3_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_httpclass_profile_943dc4367c31ce3fcb5cc6303cf1ca1c_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_httpclass_profile_943dc4367c31ce3fcb5cc6303cf1ca1c_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_httpclass_profile_a52c7abdb1ea0861eae039820473b9a4_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_httpclass_profile_a52c7abdb1ea0861eae039820473b9a4_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_last_hop_pool_190aae6585f7d07de3d35abd29cc2809_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_last_hop_pool_190aae6585f7d07de3d35abd29cc2809_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_last_hop_pool_40d082fc712d28294cc2d8d0a826dacc_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_last_hop_pool_40d082fc712d28294cc2d8d0a826dacc_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_list_ba4a3e43e1a6432d3705f9b33b5dd74b_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_list_ba4a3e43e1a6432d3705f9b33b5dd74b_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_persistence_profile_dd6d8e564ed77f76aef1dc70827786cf_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_persistence_profile_dd6d8e564ed77f76aef1dc70827786cf_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_persistence_profile_f4aa66ae0a04ee908c66e6ba2cd9b9e5_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_persistence_profile_f4aa66ae0a04ee908c66e6ba2cd9b9e5_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_profile_d5d685210e22e595d090d73751eb040e_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_profile_d5d685210e22e595d090d73751eb040e_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_protocol_4398dbaabf93cb6953c6a96a3bea50e0_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_protocol_4398dbaabf93cb6953c6a96a3bea50e0_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_protocol_69ef7e15d5028fe6a721747adba62950_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_protocol_69ef7e15d5028fe6a721747adba62950_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_rate_class_1c90fa5d61bbdf7b294ba38e1af7bc1b_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_rate_class_1c90fa5d61bbdf7b294ba38e1af7bc1b_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_rate_class_b368e22d769f1aea4fd93fc5afa3a1d1_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_rate_class_b368e22d769f1aea4fd93fc5afa3a1d1_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_rule_66492b11f71a630410592b270bdb5d2f_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_rule_66492b11f71a630410592b270bdb5d2f_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_rule_9f887fbec09cc6d9b843c5be280d9417_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_rule_9f887fbec09cc6d9b843c5be280d9417_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_snat_pool_e1fef82a3cfb394e0eef2ff5186d0858_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_snat_pool_e1fef82a3cfb394e0eef2ff5186d0858_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_snat_pool_f5928b9fc16cd8db5899e3dfec185832_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_snat_pool_f5928b9fc16cd8db5899e3dfec185832_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_snat_type_7df1b69d337b57609ba539c928af66c0_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_snat_type_7df1b69d337b57609ba539c928af66c0_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_snat_type_c03a20ccca6f092bd703b53b291e960d_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_snat_type_c03a20ccca6f092bd703b53b291e960d_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_source_port_behavior_ac67125cf05025a11932f80c7fcf8e96_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_source_port_behavior_ac67125cf05025a11932f80c7fcf8e96_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_source_port_behavior_d9735706fc3d26ed4a6296bd6be4e3df_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_source_port_behavior_d9735706fc3d26ed4a6296bd6be4e3df_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_statistics_03fa5dd62e9556caa0378503d886a8d6_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_statistics_03fa5dd62e9556caa0378503d886a8d6_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_statistics_e9c14c62964e7d32652b2693508d29de_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_statistics_e9c14c62964e7d32652b2693508d29de_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_translate_address_state_0376996f05fb7f314e18125d26f5c272_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_translate_address_state_0376996f05fb7f314e18125d26f5c272_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_translate_address_state_7a93646af306b72ca6c790cd0282282a_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_translate_address_state_7a93646af306b72ca6c790cd0282282a_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_translate_port_state_5152b412671e10e1f557fea0b8fc1121_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_translate_port_state_5152b412671e10e1f557fea0b8fc1121_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_translate_port_state_b0a849b090b7c60f67dbf7251951b28b_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_translate_port_state_b0a849b090b7c60f67dbf7251951b28b_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_type_2656e4f80e247e1ce0a3ce22170cf465_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_type_2656e4f80e247e1ce0a3ce22170cf465_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_type_eb31a13af41d3d50b7905e47ac38c414_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_type_eb31a13af41d3d50b7905e47ac38c414_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_version_3533ba846bfd35a740bb88b6a8e2ffbc_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_version_3533ba846bfd35a740bb88b6a8e2ffbc_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_vlan_0e71725e2caaaa8cf8027e1a676a2057_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_vlan_0e71725e2caaaa8cf8027e1a676a2057_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_vlan_c940ff0f2ce4b342a6e4127bc581f503_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_vlan_c940ff0f2ce4b342a6e4127bc581f503_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_wildmask_26e70163d1a2debd816ae045db08756e_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_wildmask_26e70163d1a2debd816ae045db08756e_response.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_wildmask_7b821f8258ae4348d14305b518e0ffdc_request.xml",
     "spec/fixtures/soap/xml/IControl.LocalLB.VirtualServer.get_wildmask_7b821f8258ae4348d14305b518e0ffdc_response.xml",
     "spec/fixtures/wsdl/wsdl_fixture.rb",
     "spec/fixtures/wsdl/wsdl_fixture.yml",
     "spec/fixtures/wsdl/xml/IControl.GlobalLB.Rule.xml",
     "spec/http_stubs.rb",
     "spec/icontrol_local_lb_pool_spec.rb",
     "spec/icontrol_local_lb_profile_http_class_spec.rb",
     "spec/icontrol_local_lb_rule_spec.rb",
     "spec/icontrol_local_lb_virtual_server_spec.rb",
     "spec/icontrol_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/magec/icontrol}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A ruby client to the BigIP F5}
  s.test_files = [
    "spec/icontrol_local_lb_pool_spec.rb",
     "spec/icontrol_local_lb_profile_http_class_spec.rb",
     "spec/http_stubs.rb",
     "spec/icontrol_local_lb_virtual_server_spec.rb",
     "spec/fixtures/soap/soap_fixture.rb",
     "spec/fixtures/wsdl/wsdl_fixture.rb",
     "spec/fixtures/endpoint_helper.rb",
     "spec/spec_helper.rb",
     "spec/icontrol_local_lb_rule_spec.rb",
     "spec/icontrol_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_runtime_dependency(%q<savon>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_dependency(%q<savon>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    s.add_dependency(%q<savon>, [">= 0"])
  end
end

